# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Custom vars
version:          2.1.0

github:           metadata

repository:       dagope/dagope.github.io
userdisqus:       dagope

# Setup
author:
  name:           "David Gonzalo"
  url:            https://twitter.com/dagope
  twitter:        dagope

paginate:         5

title:            "dagope's blog"
tagline:          "Diario de abordo Dagope"
description:      "Mira, detrás de ti, un mono de tres cabezas."
locale:           es_es
encoding:         utf-8
url:              https://dagope.github.io
baseurl:          https://dagope.github.io/  
google_analytics: UA-107487057-1
icon:             /defaulticon.jpg
