# This is a basic workflow that is manually triggered

name: Schedule Rebuild GithubPages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Person to greet'
        default: 'Go'
  schedule:
   - cron: '45 15 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $GITHUB_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          GITHUB_TOKEN : ${{ secrets.TOKENGITHUB  }}
