# Manually triggered and Schedyle by cron expression

name: Schedule Rebuild GithubPages

on:
  workflow_dispatch:
    
  schedule:
   - cron: '15 5 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $GITHUB_TOKEN"
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          GITHUB_TOKEN : ${{ secrets.TOKENGITHUB  }}
