name: Build every day

on:
  schedule:
   - cron: '15 15 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.GITHUB_TOKEN  }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/dagope/dagope.github.io/pages/builds"
